name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t pvern/nodejs-app-ec2-docker-cicd:latest .

      - name: Publish image to Docker Hub
        run: docker push pvern/nodejs-app-ec2-docker-cicd:latest
   
  deploy:
    needs: build
    runs-on: [ip-172-31-39-14]
    steps:

      - name: Pull image from Docker Hub
        run: docker pull pvern/nodejs-app-ec2-docker-cicd:latest

      - name: Delete old container
        run: docker rm -f nodejs-app-ec2-docker-cicd-container || true

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-ec2-docker-cicd-container pvern/nodejs-app-ec2-docker-cicd:latest
